#----------------------------------------------------------------------------
# Kafka Connect configuration
#----------------------------------------------------------------------------
connect:
  enabled: true
  clusters:
    - name: kafka-connect
      url: http://kafka-connect:8083
      tls:
        enabled: false
#----------------------------------------------------------------------------
# Kafka configuration
#----------------------------------------------------------------------------
kafka:
  brokers: ["kafka:9093"]
  tls:
    enabled: false
  schemaRegistry:
    enabled: true
    urls: ["http://schema-registry:8081"]
#----------------------------------------------------------------------------
# Server settings
#----------------------------------------------------------------------------
server:
  listenAddress: "0.0.0.0"
  listenPort: 8050